# CI/CD configuration for VGG Image Search Engine (VISE)
# https://gitlab.com/vgg/vise
# https://www.robots.ox.ac.uk/~vgg/software/vise/
#
# Author: Abhishek Dutta <adutta@robots.ox.ac.uk>
# Date  : 13-June-2021

stages:
  - build
  - test
  - all

Windows-10-Build:
  stage: build
  tags:
    - vgg-windows-10-builder
  script:
    - echo "Building VISE for Windows 64 bit"
    - git -C C:\Users\tlm\code\vise\ pull origin master 
    - cmd.exe /Q /C "C:\Users\tlm\code\vise\scripts\dist\build-win64.cmd"

Windows-10-Test:
  stage: test
  tags:
    - vgg-windows-10-builder
  script:
    - echo "Testing VISE on Oxford-Buildings-100 subset"
    - C:\Users\tlm\build\vise\release\Win64\tests\Release\test_oxford_buildings oxford-buildings-100 "C:\Users\tlm\tests\vise\relja_retrival\oxford-buildings-100\images" "C:\Users\tlm\tests\vise\relja_retrival\oxford-buildings-100\gt" 0.03 "C:\Users\tlm\build\vise\tests"

Debian-Build:
  stage: build
  tags:
    - vgg-Linux-builder
  script:
    - echo "Buildings VISE for Debian Linux ..."
    - git clone https://gitlab.com/vgg/vise.git
    - cd vise && mkdir cmake_build && cd cmake_build && /home/gitlab-runner/dep/vise/bin/cmake -DCMAKE_PREFIX_PATH=/home/gitlab-runner/dep/vise/ ../src && make -j

Debian-Test:
  stage: test
  tags:
    - vgg-Linux-builder
  script:
    - echo "Testing VISE on Oxford Buildings 100 subset ..."
    - git clone https://gitlab.com/vgg/vise.git
    - cd vise && mkdir cmake_build && cd cmake_build && /home/gitlab-runner/dep/vise/bin/cmake -DCMAKE_PREFIX_PATH=/home/gitlab-runner/dep/vise/ ../src && make -j
    - if [ -d "/tmp/vise/test/" ]; then rm -fr /tmp/vise/test; fi
    - mkdir -p /tmp/vise/test && tests/test_oxford_buildings oxford-buildings-100 /home/gitlab-runner/dataset/oxford_buildings/oxford-buildings-100/images/ /home/gitlab-runner/dataset/oxford_buildings/oxford-buildings-100/gt/ 0.03 /tmp/vise/test/

MacOS-Build:
  stage: build
  tags:
    - vgg-MacOS-builder
  script:
    - echo "Buildings VISE for MacOS"
    - cd /Users/adutta/code/vise/cmake_build && git pull origin master && make -j

MacOS-Test:
  stage: test
  tags:
    - vgg-MacOS-builder
  script:
    - echo "Testing VISE on Oxford-Buildings-100 subset"
    - /Users/adutta/code/vise/cmake_build/tests/test_oxford_buildings oxford-buildings-100 /Users/adutta/dataset/oxford_buildings/oxford-buildings-100/images/ /Users/adutta/dataset/oxford_buildings/oxford-buildings-100/gt/ 0.03 /Users/adutta/tmp/
