/** @file project_html_resources.h
 *  @brief HTML resources to build and serve a web browser based minimal user interface for VISE
 *  @author Abhishek Dutta <adutta _at_ robots.ox.ac.uk>
 *  @date 2 Feb. 2020
 */
#ifndef PROJECT_HTML_RESOURCES_H
#define PROJECT_HTML_RESOURCES_H

namespace vise {
  const char *HTML_HEAD = R"HTML_STR(<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
    <meta http-equiv="Pragma" content="no-cache" />
    <meta http-equiv="Expires" content="0" />
    <title></title>
    <meta name="author" content="VGG Image Search Engine (VISE)">
    <meta name="description" content="A project created using VGG Image Search Engine (VISE). More details are available at the following website: http://www.robots.ox.ac.uk/~vgg/software/vise/">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    <link rel="stylesheet" type="text/css" href="/project.css">
  </head>
  <!-- This HTML file was automatically generated by "src/vise/project_html_resources.h" file -->
)HTML_STR";

}
#endif
